#db: awd.db
debug: false
time:
  start: '9:00'
  # each round time(minutes)
  interval: 5
platform:
#  submit flag by `curl` command,we will replace {flag} with value
  curl: curl  http://127.0.0.1:8000/submit?flag={flag}&token=fc067281e151a0b929f5056f22298490
#  submit flag interval(milliseconds)
#  interval: 500
#  ------------------------------------------------------------------------------------------
# submit flag by python script,just define the function: submit(flag)
# example:
#
# import requests
# def submit(flag: str) -> requests.Response:
#     return requests.post(f'https://xxxx.com/flag?flag={flag}')
#
#  python: submit.py
# ------------------------------------------------------------------------------------------
# timeout when submit flag to platform
#  timeout: 3
# the success text what the platform return when submit flag successfully,we will check it
#  success_text:
#    - 'Success'
#    - 'Flag Accepted'
attack:
#  use the regex to search flag value after payload attacked
  regx: \w{32}
#  dir: payloads
#  thread: 8
challenge:
# ----------------------------------------------------
#  we will generate challenges with the under params
  easyWeb:
    ips: 172.18.1.1~10
    include: 172.18.1.8
    exclude: 172.18.1.4
  hardWeb:
    ips: 172.18.2.1~10
    include: 172.18.2.8
    exclude: 172.18.2.4
# ----------------------------------------------------
#  Or you can input all the challenges' address
#  raw:
#    easyWeb:
#      - 10.0.1.8
#      - 10.0.2.8
#      - 10.0.3.8
#      - 10.0.4.8
#      - 10.0.5.8
#      - 10.0.6.8
#    hardWeb:
#      - 10.0.1.9
#      - 10.0.2.9
#      - 10.0.3.9
#      - 10.0.4.9
#      - 10.0.5.9
#      - 10.0.6.9